### ISSUE TITLE
Error after starting streamlit application - cannot import name 'RDTClassifier' from 'hana_ml.algorithms.pal.tree'

### ISSUE THREAD

**Issue by ArmaanSingla92** [dan0nchik/SAP-HANA-AutoML#10]
cannot import name 'RDTClassifier' from 'hana_ml.algorithms.pal.tree'

**Comment by ArmaanSingla92** [comment]
I had hana-ml installed earlier so due to which i faced this issue. After re-installing hana-ml again , i resolved the issue

**Comment by dan0nchik** [comment]
Hello!
You can access Streamlit app at
https://share.streamlit.io/dan0nchik/sap-hana-automl/main/web.py where you don't need to install any dependencies, it works out of the box
